@startuml
!include style.puml
skinparam ArrowFontStyle plain

title "Sort Command Sequence Diagram"

actor User

' -- Box for Logic layer
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":SortCommandParser" as SortCommandParser LOGIC_COLOR
participant ":SortCommand" as SortCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

' -- Box for Model layer
box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

User -> LogicManager: "sort"
activate LogicManager

LogicManager -> AddressBookParser: parseCommand("sort")
activate AddressBookParser

' Create the SortCommandParser
AddressBookParser -> AddressBookParser: new SortCommandParser()
create SortCommandParser
AddressBookParser -> SortCommandParser
activate SortCommandParser

' Return to show the parser was constructed
SortCommandParser --> AddressBookParser
deactivate SortCommandParser
' Hidden arrow to position the destroy marker

SortCommandParser -[hidden]-> AddressBookParser

destroy SortCommandParser

' Now call parse(...) on the newly created parser
AddressBookParser -> SortCommandParser: parse("sort")

activate SortCommandParser
SortCommandParser -> SortCommandParser: parse("sort")
' Create and return new SortCommand
create SortCommand
SortCommandParser -> SortCommand
activate SortCommand

SortCommand --> SortCommandParser
deactivate SortCommand

SortCommandParser --> AddressBookParser : s
deactivate SortCommandParser
SortCommandParser -[hidden]-> AddressBookParser
destroy SortCommandParser

AddressBookParser --> LogicManager : s
deactivate AddressBookParser

LogicManager -> SortCommand : execute(m)
activate SortCommand

SortCommand -> Model : sortPersonsByName()
activate Model

Model -> Model : reorder internal person list
deactivate Model

create CommandResult
SortCommand -> CommandResult
activate CommandResult

CommandResult --> SortCommand
deactivate CommandResult

SortCommand --> LogicManager : r
deactivate SortCommand

[<--LogicManager
deactivate LogicManager
@enduml
