@startuml

title "Sort Command Sequence Diagram"

actor User

User -> Logic: "sort"
activate Logic

Logic -> AddressBookParser: parseCommand("sort")
activate AddressBookParser

' AddressBookParser creates a new SortCommandParser
AddressBookParser -> AddressBookParser: new SortCommandParser()
create SortCommandParser
activate SortCommandParser

AddressBookParser -> SortCommandParser: parse("sort")
SortCommandParser--> SortCommandParser: parse("sort")
SortCommandParser --> AddressBookParser: new SortCommand()
deactivate SortCommandParser

AddressBookParser --> Logic: SortCommand
deactivate AddressBookParser

Logic -> SortCommand: execute()
activate SortCommand

SortCommand -> Model: sortPersonsByName()
activate Model
Model -> Model: reorder internal person list
deactivate Model

SortCommand --> Logic: CommandResult("Sorted all persons by name.")
deactivate SortCommand

Logic -> User: display CommandResult
deactivate Logic

@enduml
